import Head from 'next/head'
import Footer from '../components/common/Footer'
import Navigation from '../components/common/Navigation'
import Gallery from '../components/gallery/Gallery'
import Hero from '../components/hero/Hero'
import Middle from '../components/middle/Middle'
import Preview from '../components/preview/Preview'
import Township from '../components/township/Township'
import Location from '../components/location/Location'
import Contact from '../components/contact/Contact'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Assetz Marq</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/Marq-Logo-Original.jpg" />
      </Head>

      <Navigation />

      <main>
        <Hero />
        <Township />
        <Middle />
        <Gallery />
        <Preview />
        <Location />
        <Contact />
      </main>

      <Footer />
    </div>
  )
}
