import Head from 'next/head'
import Footer from '../components/common/Footer'
import Navigation from '../components/common/Navigation'
import Hero from '../components/hero/Hero'
import Township from '../components/township/Township'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Assetz Marq</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navigation />

      <main>
        <Hero />
        <Township />
      </main>

      <Footer />
    </div>
  )
}
